### ISSUE TITLE
bin target location ??

### ISSUE THREAD

**Issue by doyousketch2** [simias/psx-rs#36]
Do you run from the rustation dir, or do you have to change to another dir?

    eli@hp-pav ~/ROMS/rustation $ cargo build --release
      Compiling rustation v0.0.3 (file:///home/eli/ROMS/rustation)
        Finished release [optimized] target(s) in 26.17 secs

    eli@hp-pav ~/ROMS/rustation $ cargo run --release /home/eli/ROMS/BIOS/PSX/SCPH-1001.BIN
    error: a bin target must be available for `cargo run`

    eli@hp-pav ~/ROMS/rustation $ cd target/release
    eli@hp-pav ~/ROMS/rustation/target/release $ cargo run /home/eli/ROMS/BIOS/PSX/SCPH-1001.BIN
    error: a bin target must be available for `cargo run`

**Comment by mlafeldt** [comment]
That happens because rustation [is built as a lib](https://github.com/simias/rustation/blob/2e9723262a2fae099c11830beff9718c998903c5/Cargo.toml#L31-L33) ~~and has a main function at [a non-standard location](https://github.com/simias/rustation/blob/master/build.rs).~~ (that's only used for building)

Not sure why there's no `src/bin/main.rs`. @simias

**Comment by simias** [comment]
What would the bin do? There's no frontend code in there, only emulation.

You can use https://github.com/simias/rustation-libretro to build a libretro core using this crate for the actual emulation. This still won't generate a bin, but rather a .so that you can load in RetroArch or any other libretro player.

Sorry for the late reply, I haven't been keeping a close look on github lately.

**Comment by doyousketch2** [comment]
If it doesn't compile to runnable code, why would your Readme.md say:

`If the build is succesful you can run the emulator using:`

`cargo run --release /path/to/SCPH1001.BIN`

**Comment by simias** [comment]
Uh, because it's severely outdated. I'll update it, thanks for pointing it out.
